### ISSUE TITLE
Change layer styling

### ISSUE THREAD

**Issue by CindyvdVries** [openearth/vegetatiemonitor#21]
Change the style using mapbox studio styles

- [ ] vegetatielegger
- [ ] stroombanen
- [ ] kadaster

**Comment by Adriaanse** [comment]
Vegetatie legger en stroombanen zijn al gedaan voor issue #5 

De kadaster polygonen kaart heeft issues, overlappende polygonen met verschillende eigenaren, dat moet met RWS besproken worden.
