### ISSUE TITLE
Apply style used by RWS vegetatielegger for Mapbox

### ISSUE THREAD

**Issue by gena** [openearth/vegetatiemonitor#5]

**Comment by gena** [comment]
See https://www.rijkswaterstaat.nl/water/waterbeheer/bescherming-tegen-het-water/waterkeringen/leggers/vegetatielegger/index.aspx

![image](https://user-images.githubusercontent.com/169821/37028721-4e07b5e6-2135-11e8-9221-dbea72d3d1eb.png)

**Comment by Adriaanse** [comment]
Eerste versie gereed, waarbij de stroombanen kaart half transparant erover heen gelegd kan worden om de licht/donker verdeling in de legenda te tonen.

**Comment by gena** [comment]
How do I test it? Is it automatically deployed on GitHub now?

**Comment by Adriaanse** [comment]
It has been deployed: http://www.openearth.nl/vegetatiemonitor/
